name: Lint

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CI: true
        
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
            
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          # run_install: true

      - name: Use Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Run lint
        run: pnpm -r run lint